### ISSUE TITLE
Impossible to make a potion itemstack with only ItemBuilder

### ISSUE THREAD

**Issue by ItsArt3x54** [Raft08/CraftyBuilder#2] opened 2023-11-27 15:32 UTC
Normaly to do a potion itemStack you do
```java
ItemStack itemStack = new ItemStack(Material.POTION)
PotionMeta potionMeta = (PotionMeta) itemStack.getItemMeta();
potionMeta.setBasePotionData(new PotionData(PotionEffectType.SPEED, 99999, 0));
itemStack.setItemMeta(potionMeta);
```
But its impossible using only ItemBuilder.

**Comment by BelgianDev** [comment] 2023-11-30 07:51
Duplicate or pretty similar issue of #1, Please just add a comment to the already existing issue next time.

**Comment by Raft08** [comment] 2023-11-30 07:52
Duplicate of #1, Please just add a comment to the already existing issue.

**Closed as completed** 2023-11-30 07:53 UTC
Labels: duplicate
